# Generated by Django 4.1.7 on 2023-04-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortcuts',
            fields=[
                ('Shortcut_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30, null=True)),
                ('Description', models.TextField(max_length=255, null=True)),
                ('Is_Enable', models.IntegerField(null=True)),
                ('Created_on', models.DateTimeField(null=True)),
                ('Created_by', models.IntegerField(null=True)),
                ('Updated_on', models.DateTimeField(null=True)),
                ('Updated_by', models.IntegerField(null=True)),
            ],
        ),
    ]
