# Generated by Django 4.0.5 on 2023-04-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocompleteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(blank=True, max_length=30, null=True)),
                ('Description', models.TextField(blank=True, max_length=250)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('Updated_on', models.DateField(blank=True, null=True)),
                ('Updated_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shortcuts',
            name='Shortcut_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shortcuts',
            name='Company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Company_ref', to='autocompleteapp.company'),
        ),
    ]
