# Generated by Django 4.0.5 on 2023-04-26 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocompleteapp', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Company_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Company_no', to='autocompleteapp.company'),
        ),
    ]
